#!/bin/bash

mkdir -p logs/predicate/wn18/

./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 1 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 10 --discriminator-epochs 10 --adv-weight 100 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_ASR_10_1.txt 2>&1
./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 1 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 10 --discriminator-epochs 10 --adv-weight 0 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_10_1.txt 2>&1

./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.9 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 10 --discriminator-epochs 10 --adv-weight 100 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_ASR_10_0.9.txt 2>&1
./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.9 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 10 --discriminator-epochs 10 --adv-weight 0 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_10_0.9.txt 2>&1

./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.8 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 10 --discriminator-epochs 10 --adv-weight 100 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_ASR_10_0.8.txt 2>&1
./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.8 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 10 --discriminator-epochs 10 --adv-weight 0 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_10_0.8.txt 2>&1

./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.7 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 10 --discriminator-epochs 10 --adv-weight 100 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_ASR_10_0.7.txt 2>&1
./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.7 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 10 --discriminator-epochs 10 --adv-weight 0 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_10_0.7.tx 2>&1

./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.6 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 10 --discriminator-epochs 10 --adv-weight 100 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_ASR_10_0.6.txt 2>&1
./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.6 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 10 --discriminator-epochs 10 --adv-weight 0 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_10_0.6.txt 2>&1

./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.5 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 10 --discriminator-epochs 10 --adv-weight 100 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_ASR_10_0.5.txt 2>&1
./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.5 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 10 --discriminator-epochs 10 --adv-weight 0 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_10_0.5.txt 2>&1

./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 1 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 0 --discriminator-epochs 10 --adv-weight 100 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_ASR_0_1.txt 2>&1
./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 1 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 0 --discriminator-epochs 10 --adv-weight 0 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_0_1.txt 2>&1

./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.9 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 0 --discriminator-epochs 10 --adv-weight 100 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_ASR_0_0.9.txt 2>&1
./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.9 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 0 --discriminator-epochs 10 --adv-weight 0 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_0_0.9.txt 2>&1

./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.8 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 0 --discriminator-epochs 10 --adv-weight 100 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_ASR_0_0.8.txt 2>&1
./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.8 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 0 --discriminator-epochs 10 --adv-weight 0 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_0_0.8.txt 2>&1

./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.7 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 0 --discriminator-epochs 10 --adv-weight 100 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_ASR_0_0.7.txt 2>&1
./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.7 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 0 --discriminator-epochs 10 --adv-weight 0 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_0_0.7.tx 2>&1

./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.6 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 0 --discriminator-epochs 10 --adv-weight 100 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_ASR_0_0.6.txt 2>&1
./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.6 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 0 --discriminator-epochs 10 --adv-weight 0 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_0_0.6.txt 2>&1

./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.5 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 0 --discriminator-epochs 10 --adv-weight 100 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_ASR_0_0.5.txt 2>&1
./bin/adv-cli.py --train data/wn18/wordnet-mlj12-train.txt --valid data/wn18/wordnet-mlj12-valid.txt --test data/wn18/wordnet-mlj12-test.txt --clauses data/wn18/clauses/clauses_0.9.pl --nb-epochs 100 --lr 0.1 --nb-batches 10 --model ComplEx --similarity dot --margin 1 --embedding-size 200 --subsample-size 0.5 --loss hinge --adv-lr 0.1 --adv-init-ground --adversary-epochs 0 --discriminator-epochs 10 --adv-weight 0 --adv-batch-size 10 --debug-results > logs/predicate/wn18/ComplEx_0_0.5.txt 2>&1
